### ISSUE TITLE
error App@1.0.0 prod: `cross-env NODE_ENV=production webpack --progress -p`

### ISSUE THREAD

**Issue by strongui** [kentcdodds/cross-env#101]
My scrip has always worked in the past, and it works if I remove cross-env NODE_ENV=production, but the problem is, since I'm on a windows machine, it's not actually setting the envorioment to production, so the generated code is huge.

Here is the log: 

```
info it worked if it ends with ok
verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
verbose cli   'C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
verbose cli   'run',
verbose cli   'prod' ]
info using npm@4.4.4
info using node@v6.10.2
verbose run-script [ 'preprod', 'prod', 'postprod' ]
info lifecycle App@1.0.0~preprod: App@
silly lifecycle App@1.0.0~preprod: no script for preprod, continuing
info lifecycle App@1.0.0~prod: App@1.0.0
verbose lifecycle App@1.0.0~prod: unsafe-perm in lifecycle true
verbose lifecycle App@1.0.0~prod: PATH: C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\myuser\workspace\app-amir_playground-main\shared\assets\node_modules\.bin;C:\Users\myuser\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Druide\Antidote 8\Programmes64\;C:\Program Files (x86)\Druide\Antidote 8\Programmes32\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\myuser\bin\Sencha\Cmd;C:\Ruby23-x64\bin;C:\Users\myuser\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\myuser\AppData\Roaming\npm
verbose lifecycle App@1.0.0~prod: CWD: C:\Users\myuser\workspace\app-amir_playground-main\shared\assets
silly lifecycle App@1.0.0~prod: Args: [ '/d /s /c',
silly lifecycle   'cross-env NODE_ENV=production webpack --progress -p' ]
silly lifecycle App@1.0.0~prod: Returned: code: 1  signal: null
info lifecycle App@1.0.0~prod: Failed to exec prod script
verbose stack Error: App@1.0.0 prod: `cross-env NODE_ENV=production webpack --progress -p`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
verbose stack     at emitTwo (events.js:106:13)
verbose stack     at EventEmitter.emit (events.js:191:7)
verbose stack     at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
verbose stack     at emitTwo (events.js:106:13)
verbose stack     at ChildProcess.emit (events.js:191:7)
verbose stack     at maybeClose (internal/child_process.js:886:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
verbose pkgid App@1.0.0
verbose cwd C:\Users\myuser\workspace\app-amir_playground-main\shared\assets
verbose Windows_NT 10.0.14393
verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
verbose node v6.10.2
verbose npm  v4.4.4
error code ELIFECYCLE
error errno 1
error App@1.0.0 prod: `cross-env NODE_ENV=production webpack --progress -p`
error Exit status 1
error Failed at the App@1.0.0 prod script 'cross-env NODE_ENV=production webpack --progress -p'.
error Make sure you have the latest version of node.js and npm installed.
error If you do, this is most likely a problem with the App package,
error not with npm itself.
error Tell the author that this fails on your system:
error     cross-env NODE_ENV=production webpack --progress -p
error You can get information on how to open an issue for this project with:
error     npm bugs App
error Or if that isn't available, you can get their info via:
error     npm owner ls App
error There is likely additional logging output above.
verbose exit [ 1, true ]
```

**Comment by strongui** [comment]
Ok, I think it's not related to this package after all. I tried setting the environmental variable manually (SET NODE_ENV=production) and then running my script, and it throws an error as well.
