### ISSUE TITLE
Error: spawn babel-node ENOENT

### ISSUE THREAD

**Issue by pavel06081991** [kentcdodds/cross-env#105]
I'm using cross-env like this in npm script:

`"test:unit": "cross-env BABEL_ENV=production babel-node node_modules/karma/bin/karma start karma.conf.js"`

When I run npm run test:unit I get the error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel-node ENOENT
    at notFoundError (D:\work\my_projects\react-starter\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\work\my_projects\react-starter\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\work\my_projects\react-starter\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```
The error is in cross--spawn npm module, but I found that cross env uses this package. Can you help me to understand if this issue is related to cross-env?

**Comment by hgwood** [comment]
`ENOENT` means "error: no entry". It means a file cannot be found. In your case, it is `babel-node` that does not exist. This has probably nothing to do with cross-env so I'm closing the issue but you may ask further questions if you need.

**Comment by pavel06081991** [comment]
@hgwood, the babel-node is installed in local node_modules. I thought maybe cross-env is that who runs babel-env?

**Comment by kentcdodds** [comment]
Does this work without cross-env?
