### ISSUE TITLE
Error adding contributor: Cannot find module 'all-contributors-cli/cli'

### ISSUE THREAD

**Issue by iki** [kentcdodds/cross-env#168]
- `cross-env` version: master
- `node` version: 9.4.0 
- `npm` (or `yarn`) version: 5.6.0
- `os`: Microsoft Windows [Version 10.0.15063]

What you did:
```
git checkout https://github.com/kentcdodds/cross-env
cd cross-env
npm install
npm run validate
npm run add-contributor
```

What happened:

```
> cross-env@0.0.0-semantically-released add-contributor C:\Users\iki\code\cross-env
> kcd-scripts contributors add

module.js:557
    throw err;
    ^

Error: Cannot find module 'all-contributors-cli/cli'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (C:\Users\iki\..js\cross-env\node_modules\kcd-scripts\dist\scripts\contributors.js:7:33)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'add-contributor' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'preadd-contributor',
4 verbose run-script   'add-contributor',
4 verbose run-script   'postadd-contributor' ]
5 info lifecycle cross-env@0.0.0-semantically-released~preadd-contributor: cross-env@0.0.0-semantically-released
6 info lifecycle cross-env@0.0.0-semantically-released~add-contributor: cross-env@0.0.0-semantically-released
7 verbose lifecycle cross-env@0.0.0-semantically-released~add-contributor: unsafe-perm in lifecycle true
8 verbose lifecycle cross-env@0.0.0-semantically-released~add-contributor: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\iki\code\cross-env\node_modules\.bin;C:\Users\iki\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\iki\AppData\Roaming\npm;C:\Program Files\nodejs;...
9 verbose lifecycle cross-env@0.0.0-semantically-released~add-contributor: CWD: C:\Users\iki\code\cross-env
10 silly lifecycle cross-env@0.0.0-semantically-released~add-contributor: Args: [ '/d /s /c', 'kcd-scripts contributors add' ]
11 silly lifecycle cross-env@0.0.0-semantically-released~add-contributor: Returned: code: 1  signal: null
12 info lifecycle cross-env@0.0.0-semantically-released~add-contributor: Failed to exec add-contributor script
13 verbose stack Error: cross-env@0.0.0-semantically-released add-contributor: `kcd-scripts contributors add`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid cross-env@0.0.0-semantically-released
15 verbose cwd C:\Users\iki\code\cross-env
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "add-contributor"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error cross-env@0.0.0-semantically-released add-contributor: `kcd-scripts contributors add`
22 error Exit status 1
23 error Failed at the cross-env@0.0.0-semantically-released add-contributor script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Reproduction repository: https://github.com/kentcdodds/cross-env

Problem description: Cannot find module 'all-contributors-cli/cli'. The file `C:\Users\iki\code\cross-env\node_modules\all-contributors-cli\dist\cli.js` is present though.

Suggested solution: Check if `all-contributors-cli` installs correctly on Windows.

**Comment by iki** [comment]
Workaround: run directly `node_modules\.bin\all-contributors.cmd`.
