### ISSUE TITLE
the CLI seems to be missing a dependency, `which`

### ISSUE THREAD

**Issue by SKalt** [kentcdodds/cross-env#199]
- `cross-env` version: 5.2.0, 5.1.0 tested
- `node` version: 10.6.0
- `npm` (or `yarn`) version: yarn 1.13.0

Relevant code or config

```sh
$ npx cross-env
# Error: Cannot find module '../lib/utils/unsupported.js'
#     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
#     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
#     at Module.require (internal/modules/cjs/loader.js:637:17)
#     at require (internal/modules/cjs/helpers.js:20:18)
#     at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
#     at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
#     at Module._compile (internal/modules/cjs/loader.js:689:30)
#     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
#     at Module.load (internal/modules/cjs/loader.js:599:32)
#     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
$ yarn list --pattern cross-env
# └─ cross-env@5.2.0
# ✨  Done in 0.81s.
```

What you did:
`yarn`

What happened:

After a `yarn upgrade other-dependency`, this one began missing `which`/

Reproduction repository:

```sh
#!/usr/bin/env bash
mkdir repoduction-repo && cd $_ && git init
yarn add --dev cross-env
npx cross-env
```

Problem description:
Missing dependency, looks like.

Suggested solution:
Re-add `which` as a dependency.

**Comment by kentcdodds** [comment]
Sorry, I cannot reproduce:

```
~/Desktop 🤯
$ mkdir repoduction-repo && cd $_ && git init
/Users/kentcdodds/Desktop/repoduction-repo
Initialized empty Git repository in /Users/kentcdodds/Desktop/repoduction-repo/.git/
~/Desktop/repoduction-repo 🤯
$ yarn add --dev cross-env
npx cross-env
yarn add v1.12.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
⠂ cross-env
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.15.2", while you're on "1.12.3".
info To upgrade, run the following command:
$ brew upgrade yarn
success Saved 10 new dependencies.
info Direct dependencies
└─ cross-env@5.2.0
info All dependencies
├─ cross-env@5.2.0
├─ cross-spawn@6.0.5
├─ is-windows@1.0.2
├─ isexe@2.0.0
├─ nice-try@1.0.5
├─ path-key@2.0.1
├─ semver@5.6.0
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
└─ which@1.3.1
✨  Done in 0.42s.
~/Desktop/repoduction-repo 🤯
$ npx cross-env

~/Desktop/repoduction-repo 🤯
$ 
```

I'm guessing it's something else wrong in your project.

**Comment by SKalt** [comment]
Future bug-hunters: turns out some global operation nuked my installation of `npm`.
