### ISSUE TITLE
issue with nodejs in windows

### ISSUE THREAD

**Issue by omaralwi** [kentcdodds/cross-env#215]
after istall all npm packages in windows I face this problem

The system cannot find the path specified.
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\webpack\bin\webpack.js ENOENT
    at notFoundError (C:\Users\Eng Omar Alalwi\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Eng Omar Alalwi\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Eng Omar Alalwi\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\Users\Eng Omar Alalwi\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node_modules\\webpack\\bin\\webpack.js',
  path: 'node_modules\\webpack\\bin\\webpack.js',
  spawnargs: [
    '--watch',
    '--progress',
    '--hide-modules',
    '--config=node_modules/laravel-mix/setup/webpack.config.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eng Omar Alalwi\AppData\Roaming\npm-cache\_logs\2019-10-08T13_56_05_306Z-debug.log

C:\wamp64\www\Logistics_System>

**Comment by kentcdodds** [comment]
This looks unrelated to `cross-env` and it's actually related to some file not being found by the script that you're actually trying to run. Sorry.
