### ISSUE TITLE
Fresh Laravel v8.12 install, node.js - TypeError: commandConvert is not a function

### ISSUE THREAD

**Issue by ONDoubleB** [kentcdodds/cross-env#256]
- `cross-env` version:7.0
- `node` version: 15.2.0
- `npm`version: 7.0.8

What you did:

I created a fresh laravel installation, then ran npm install && npm run dev

What happened:

After a successful npm install, I get an error whilst running npm run dev:

TypeError: commandConvert is not a function

/var/www/x/node_modules/cross-env/src/index.js:15
      commandConvert(command, env, true),
      ^
TypeError: commandConvert is not a function
    at crossEnv (/var/www/x/node_modules/cross-env/src/index.js:15:7)
    at Object.<anonymous> (/var/www/x/node_modules/cross-env/src/bin/cross-env.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

Reproduction repository:

Laravel v8.12

**Comment by kentcdodds** [comment]
https://github.com/kentcdodds/cross-env/issues/257
