### ISSUE TITLE
Error: Cannot find module './command'

### ISSUE THREAD

**Issue by skalfyfan** [kentcdodds/cross-env#36]
Hi there! I see that a new update to your module was published to NPM about 5 mins ago, but it seems to have completely broken our CI build process and unit tests :(

We have the following setup within _package.json_ which runs our unit tests:
```
{
  "scripts": {
    "test": "scripts/test.sh"
  }
}
```

...and our _scripts/test.sh_ reads as follows:
```
#!/usr/bin/env bash

TEST_TYPE='unit'
[ -n "$1" ] && TEST_TYPE="$1"

NODE_ENV='development'
[ -n "$2" ] && NODE_ENV="$2"

KARMA_CONFIG='karma.'$TEST_TYPE'.conf.js'

cross-env NODE_ENV=$NODE_ENV karma start build/$KARMA_CONFIG --single-run --test-type $TEST_TYPE
```

When we run `npm run test` now we get the following error right away now:

```
> scripts/test.sh

module.js:341
    throw err;
    ^

Error: Cannot find module './command'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/paul/dev/clones/app-activations-ui/node_modules/cross-env/dist/index.js:13:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! prepaid-activations-ui@0.0.1 test: `scripts/test.sh`
npm ERR! Exit status 1
```

**Comment by skalfyfan** [comment]
Was fixed in a quick update!
