### ISSUE TITLE
cross-env 3.0 failed running on node 0.12.7

### ISSUE THREAD

**Issue by fedulovivan** [kentcdodds/cross-env#43]
Hello, just found latest version of cross-env is not able to startup with node v 0.12.7 on Linux.
Btw, same with cross-env@2 works fine.

Scanario:
1. fetch lib from npm with `npm install cross-env --save-dev`
2. run locally installed binary
```bash
johnny ~ $ node -v; ./node_modules/.bin/cross-env
v0.12.7
/home/johnny/node_modules/cross-env/dist/index.js:58
  var envVars = Object.assign({}, process.env);
                       ^
TypeError: undefined is not a function
    at getCommandArgsAndEnvVars (/home/johnny/node_modules/cross-env/dist/index.js:58:24)
    at crossEnv (/home/johnny/node_modules/cross-env/dist/index.js:22:35)
    at Object.<anonymous> (/home/johnny/node_modules/cross-env/bin/cross-env.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by kentcdodds** [comment]
Right, v3 was a breaking change because we dropped support for Node < v4.
