### ISSUE TITLE
 require(...) is not a function

### ISSUE THREAD

**Issue by huadong1989** [kentcdodds/cross-env#72]
@kentcdodds  
cross-env fails to run:

`/private/var/www/ndsm/ndsm-web/webapp/node_modules/cross-env/dist/bin/cross-env.js:4`
require('../')(process.argv.slice(2));
              ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/private/var/www/ndsm/ndsm-web/webapp/node_modules/cross-env/dist/bin/cross-env.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3`

**Comment by blade254353074** [comment]
Same issue...

```bash
require('../')(process.argv.slice(2));
              ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/SebastianBlade/Documents/Workspace/Web/git/Reantx/node_modules/cross-env/dist/bin/cross
-env.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by Pegasuz** [comment]
I also encounter this problem.
